services:
  web:
    image: pippsza/steam-diploma-web:latest
    ports:
      - "3984:3000"
    env_file: .env
    restart: unless-stopped

  bot:
    image: pippsza/steam-diploma-bot:latest
    env_file: .env
    depends_on:
      - web
    restart: unless-stopped
